# Base configs
baseurl: "http://p360dotmg.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "need to be update"

# UI configs
title: "Photography by Ando Landy"
subtitle: "See the world where I lives!"
author: "Ando Landy"
header:
 title: "Photography"
 subtitle: "by Ando Landy"
footer:
 name: "Hey there, my name is Ando Landy"
 bio: "I am a Process Technician and a Landscape Photographer from Madagascar. Love making lot of things, creating  or hacking things to suit for my uses. And know I learn to be a programmer/developper"
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/abyssDS"
